dist: trusty
language: node_js
node_js:
  - lts/*
branches:
  only:
    - gh-pages
cache:
  directories:
    - node_modules
env:
  global:
    - URL="https://w3c.github.io/pointerlock/ECHIDNA"
    - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
    - secure: "Dm+VWHjO81zybbCwdNTPxsVys73PhXTzf8r57v0ZN28kIShNDg35PJwoi7uW8IX4n9Mc+vZcVSL8eiVySuvxwkLcdb3z0anJ4dkH4EJqRpstfWfEapIfBrmE8ziDgmnhZbbKcahzlp7SjsB9ughCYMi4tzWbsba55wj0wNfPynNy83qJThQKQbeHMqzkD2ZM5/NZVV+4wztwpSYJ1Vv3AwNd+cfGqSU7Uj+/RUa4dBikdE8FGNtmEmgePc8C0+M4J90pgHIZUIg5sCnq/wFspGb6NtWz4dU4i81QdEgCSaUfpH7w6mf2ppMojg8WKgAlCXqsJSTQuz0mHJUtF+b2qY76alo8FdWkUw/wTZpwrtsgWJ+fTvDmIRMN/hVNLuB05ZkytnjoywVswqE04i5zWz465Uh2EkzREqzu839IOyzqzgyMfyp0RgxQQkNspTeJS2KyqPyfFVhxWq6ls2WrmldbOcLG8E+e57beHqg7Cq+YVaKCbpyoHvnX/4g1bPUZnhs2UvgWHsEWedW5/VW+rjzDXs4Eoq+UB7Z09oW31wWxFk4DfSOQyQJjgR6To1SFkf5YIjauJOh4P/yhnNHRbwGlhGynwu6jezncvSl9HiBHw8V2d2hposaP/AazO+Pynf0sBtcdGFoEpsC7v99NFVnXd/K2wa+TGBXCYhHGAHg="

install:
  - npm install respec-validator
script:
  - npx respec-validator --gh-user=$GH_USER --gh-token=$GH_TOKEN index.html

after_success:
  - CC="marcos@marcosc.com"
  - echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" --data "cc=$CC"
